version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: default
    main: ./cmd/synacklab
    binary: synacklab
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - '^refactor:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## What's Changed
    
    This release includes the following changes:
  footer: |
    ## Installation
    
    ### Download Binary
    Download the appropriate binary for your platform from the assets below.
    
    ### Using Go Install
    ```bash
    go install github.com/synacklab/synacklab/cmd/synacklab@{{.Tag}}
    ```
    
    ### Package Managers
    - **Debian/Ubuntu**: Download the `.deb` file and install with `sudo dpkg -i synacklab_*.deb`
    - **RHEL/CentOS/Fedora**: Download the `.rpm` file and install with `sudo rpm -i synacklab_*.rpm`
    
    ## Checksums
    All binaries are signed and checksums are provided in `checksums.txt`.

nfpms:
  - id: packages
    package_name: synacklab
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "synacklab"
    homepage: "https://github.com/synacklab/synacklab"
    maintainer: "synacklab"
    description: "A command-line tool for DevOps engineers to manage AWS SSO authentication and profile configuration"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: config.example.yaml
        dst: /etc/synacklab/config.example.yaml
        type: config|noreplace
      - src: README.md
        dst: /usr/share/doc/synacklab/README.md
      - src: LICENSE
        dst: /usr/share/doc/synacklab/LICENSE