# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synacklab < Formula
  desc "A command-line tool for DevOps engineers to manage AWS SSO authentication and profile configuration"
  homepage "https://github.com/szpuni/synacklab-cli"
  version "0.5.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.5.0/synacklab-cli_Darwin_arm64.tar.gz"
      sha256 "c1b771fe26ebad7e3f62e6311c6c7f8477a08211f5084d1a4439d311df413a83"

      def install
        bin.install "synacklab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.5.0/synacklab-cli_Darwin_x86_64.tar.gz"
      sha256 "abd8865d9b4a7cc29a8bdd94a274d0a600d9a18a159e70b916df7378d312e6fa"

      def install
        bin.install "synacklab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.5.0/synacklab-cli_Linux_arm64.tar.gz"
      sha256 "842d9ffc824fc11aa57ff2bb10f3787fe79f1dfcf9e14ef3a4b049d91a725edb"

      def install
        bin.install "synacklab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.5.0/synacklab-cli_Linux_x86_64.tar.gz"
      sha256 "5f534e4079c1d8d8f9e31d98230e8bc098e12594e5b42b7ec940664b349d37bf"

      def install
        bin.install "synacklab"
      end
    end
  end

  test do
    system "#{bin}/synacklab", "--help"
  end
end
