# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synacklab < Formula
  desc "A command-line tool for DevOps engineers to manage AWS SSO authentication and profile configuration"
  homepage "https://github.com/szpuni/synacklab-cli"
  version "0.4.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.4.0/synacklab-cli_Darwin_arm64.tar.gz"
      sha256 "0bb506a5dcb0803e3245404b6f92c9ef34b99e3a76da1293fcb561ec6c634dbc"

      def install
        bin.install "synacklab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.4.0/synacklab-cli_Darwin_x86_64.tar.gz"
      sha256 "9294f265985551b347aa438ebcccf0bb18fc349daf6aba2588dbf1ae24b217b0"

      def install
        bin.install "synacklab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.4.0/synacklab-cli_Linux_arm64.tar.gz"
      sha256 "7632f07c58867323279a42ae169bac938800df7df081c96c005772d0c8831022"

      def install
        bin.install "synacklab"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szpuni/synacklab-cli/releases/download/v0.4.0/synacklab-cli_Linux_x86_64.tar.gz"
      sha256 "98d1fe96d4537c83810bc1583bbf880e8d68140ddfc061f7250c4174bddecb62"

      def install
        bin.install "synacklab"
      end
    end
  end

  test do
    system "#{bin}/synacklab", "--help"
  end
end
