package runbook

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParse_AllAttributes(t *testing.T) {
	src := []byte("```bash {name=get_ip, capture=PUBLIC_IP, confirm=false, timeout=30s}\n" +
		"export PUBLIC_IP=$(curl -s ifconfig.me)\n" +
		"echo \"$PUBLIC_IP\"\n" +
		"```\n")

	doc, err := (&GoldmarkParser{}).Parse(src, "/tmp/runbook.md")
	require.NoError(t, err)
	require.Len(t, doc.Blocks, 1)

	step := doc.Blocks[0].Step
	require.NotNil(t, step)
	assert.Equal(t, "get_ip", step.Name)
	assert.Equal(t, "bash", step.Lang)
	assert.Equal(t, []string{"PUBLIC_IP"}, step.Capture)
	assert.False(t, step.Confirm)
	assert.Equal(t, 30*time.Second, step.Timeout)
	assert.Equal(t, "export PUBLIC_IP=$(curl -s ifconfig.me)\necho \"$PUBLIC_IP\"\n", step.Source)
	assert.Same(t, step, doc.Steps["get_ip"])
}

func TestParse_MissingAttributesUseDefaults(t *testing.T) {
	src := []byte("```bash\necho hi\n```\n")

	doc, err := (&GoldmarkParser{}).Parse(src, "/tmp/runbook.md")
	require.NoError(t, err)
	require.Len(t, doc.Blocks, 1)

	step := doc.Blocks[0].Step
	require.NotNil(t, step)
	assert.Equal(t, "step-1", step.Name)
	assert.Empty(t, step.Input)
	assert.Empty(t, step.Capture)
	assert.False(t, step.Confirm)
	assert.False(t, step.SetCwd)
	assert.Equal(t, time.Duration(0), step.Timeout)
	assert.Equal(t, "", step.Cwd)
}

func TestParse_AutoGeneratedNamesAreSequential(t *testing.T) {
	src := []byte("```bash\necho one\n```\n\n```bash\necho two\n```\n")

	doc, err := (&GoldmarkParser{}).Parse(src, "/tmp/runbook.md")
	require.NoError(t, err)
	require.Len(t, doc.Blocks, 2)

	assert.Equal(t, "step-1", doc.Blocks[0].Step.Name)
	assert.Equal(t, "step-2", doc.Blocks[1].Step.Name)
}

func TestParse_FrontmatterIsStrippedAndParsed(t *testing.T) {
	src := []byte("---\ndefault_timeout: 45s\ndanger_patterns:\n  - \"rm -rf\"\n---\n" +
		"# Title\n\n```bash {name=only}\necho hi\n```\n")

	doc, err := (&GoldmarkParser{}).Parse(src, "/tmp/runbook.md")
	require.NoError(t, err)
	assert.Equal(t, 45*time.Second, doc.Frontmatter.DefaultTimeout)
	assert.Equal(t, []string{"rm -rf"}, doc.Frontmatter.DangerPatterns)
	require.Len(t, doc.Blocks, 2)
	assert.Contains(t, doc.Blocks[0].Prose, "# Title")
	assert.NotContains(t, doc.Blocks[0].Prose, "default_timeout")
}

func TestParse_DocumentOrderPreserved(t *testing.T) {
	src := []byte("# Title\n\nSome intro text.\n\n```bash {name=first}\necho a\n```\n\n" +
		"More prose in between.\n\n```python {name=second}\nprint(1)\n```\n")

	doc, err := (&GoldmarkParser{}).Parse(src, "/tmp/runbook.md")
	require.NoError(t, err)
	require.Len(t, doc.Blocks, 4)

	kinds := make([]BlockKind, len(doc.Blocks))
	for i, b := range doc.Blocks {
		kinds[i] = b.Kind
	}
	assert.Equal(t, []BlockKind{BlockProse, BlockStep, BlockProse, BlockStep}, kinds)
	assert.Equal(t, "first", doc.Blocks[1].Step.Name)
	assert.Equal(t, "second", doc.Blocks[3].Step.Name)
	assert.Contains(t, doc.Blocks[0].Prose, "# Title")
	assert.Contains(t, doc.Blocks[0].Prose, "Some intro text.")
	assert.Contains(t, doc.Blocks[2].Prose, "More prose in between.")
}

func TestParse_NonRunnableFenceIsStaticNotAStep(t *testing.T) {
	src := []byte("```yaml\nkey: value\n```\n\n```bash {name=real}\necho hi\n```\n")

	doc, err := (&GoldmarkParser{}).Parse(src, "/tmp/runbook.md")
	require.NoError(t, err)
	require.Len(t, doc.Blocks, 2)

	assert.Equal(t, BlockProse, doc.Blocks[0].Kind)
	assert.Contains(t, doc.Blocks[0].Prose, "```yaml")
	assert.Contains(t, doc.Blocks[0].Prose, "key: value")
	assert.NotContains(t, doc.Steps, "yaml")
	assert.Len(t, doc.Steps, 1)
	assert.Equal(t, "real", doc.Blocks[1].Step.Name)
}

func TestParse_DuplicateExplicitNamesIsError(t *testing.T) {
	src := []byte("```bash {name=dup}\necho a\n```\n\n```bash {name=dup}\necho b\n```\n")

	_, err := (&GoldmarkParser{}).Parse(src, "/tmp/runbook.md")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "dup")
}

func TestParse_MalformedAttributeSyntaxIsError(t *testing.T) {
	cases := []string{
		"```bash {name=x\necho a\n```\n",         // unbalanced brace
		"```bash {orphan}\necho a\n```\n",        // value token with no preceding key
		"```bash {confirm=maybe}\necho a\n```\n", // invalid bool
		"```bash {timeout=soon}\necho a\n```\n",  // invalid duration
	}
	for _, src := range cases {
		_, err := (&GoldmarkParser{}).Parse([]byte(src), "/tmp/runbook.md")
		assert.Error(t, err, "expected parse error for %q", src)
	}
}
